name: "CLA assistant lite"
description: "An action to handle the Contributor License Agreement"
author: "SAP"
branding:
  icon: "award"
  color: blue
inputs:
  path-to-signatures:
    description: "Give a path for storing CLAs in a json file "
    default: "./signatures/cla.json"
  branch:
    description: "provide a branch where all the CLAs are stored"
    default: "master"
  empty-commit-flag:
    description: "GitHub Actions will add empty commit whenever the user signs the CLA (optional)"
    default: true
  allowlist:
    description: "users in the allow list don't have to sign the CLA document"
  path-to-cla-document:
    description: "Fully qualified web link to cla document Example: https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md"
  remote-repository-name:
    default: ""
    description: "provide the remote repository name where all the signatures should be stored"
  remote-organization-name:
    default: ""
    description: "provide the remote organization name where all the signatures should be stored"
runs:
  using: "node12"
  main: "lib/main.js"
