name: "CLA assistant lite"
description: "An action to handle the Contributor License Agreement"
author: "SAP"
branding:
  icon: "award"
  color: blue
inputs:
  path-to-signatures:
    description: "Give a path for storing CLAs in a json file "
    default: "./signatures/cla.json"
  branch:
    description: "select a branch where all the CLAs are stored"
    default: "master"
  blockchain-storage-flag:
    description: "Optional functionality to store all the blockchain signatures in the ethirium blockchain as a smart contract"
    default: false
  empty-commit-flag:
    description: "GitHub Actions will add empty commit whenever the user signs the CLA (optional)"
    default: true
  allowlist:
    description: "Users in the allow list don't have to sign the CLA document"
  path-to-cla-document:
    description: "Fully qualified web link to cla document Example: https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md"
  signed-comment-message:
    description: "Commit message when a new contributor signs the CLA in a PR"
  request-comment-message:
    description: "Introductory message to ask new contributors to sign"
  signed-empty-commit-message:
    description: "Commit message when a new contributor signs the CLA (empty)"
  create-file-commit-message:
    description: "Commit message when a new file is created"
  all-signed-comment-message:
    description: "Commit message when everyone has signed, defaults to **CLA Assistant Lite** All Contributors have signed the CLA."
runs:
  using: "node12"
  main: "lib/main.js"
